"""initial schema with all models

Revision ID: 2849e33ec682
Revises: 
Create Date: 2026-02-12 08:12:09.838539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2849e33ec682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('owners',
    sa.Column('owner_id', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('adopted_at', sa.DateTime(), nullable=True),
    sa.Column('is_ghost', sa.Boolean(), nullable=True),
    sa.Column('adoption_tweet_url', sa.Text(), nullable=True),
    sa.Column('adoption_hash', sa.String(length=64), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('completion_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('total_earned', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('wallet_address', sa.String(length=42), nullable=True),
    sa.Column('encrypted_privkey', sa.Text(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_api_key_hash'), ['api_key_hash'], unique=True)

    op.create_table('jobs',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rubric', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('buyer_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('artifact_type', sa.String(length=20), nullable=True),
    sa.Column('deposit_tx_hash', sa.String(length=100), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('depositor_address', sa.String(length=42), nullable=True),
    sa.Column('payout_tx_hash', sa.String(length=100), nullable=True),
    sa.Column('payout_status', sa.String(length=20), nullable=True),
    sa.Column('fee_tx_hash', sa.String(length=100), nullable=True),
    sa.Column('refund_tx_hash', sa.String(length=100), nullable=True),
    sa.Column('winner_id', sa.String(length=100), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('oracle_config', sa.JSON(), nullable=True),
    sa.Column('min_reputation', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('max_submissions', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('fee_bps', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('solution_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('access_list', sa.JSON(), nullable=True),
    sa.Column('envelope_json', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('deposit_tx_hash')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_buyer_id', ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('webhooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('secret', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_agent_id'), ['agent_id'], unique=False)

    op.create_table('disputes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('filed_by', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['filed_by'], ['agents.agent_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['jobs.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disputes_task_id'), ['task_id'], unique=False)

    op.create_table('job_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('unclaimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['jobs.task_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'worker_id', name='uq_job_participant')
    )
    with op.batch_alter_table('job_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_participants_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_participants_worker_id'), ['worker_id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('oracle_score', sa.Integer(), nullable=True),
    sa.Column('oracle_reason', sa.Text(), nullable=True),
    sa.Column('oracle_steps', sa.JSON(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['jobs.task_id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_submissions_task_worker', ['task_id', 'worker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_worker_id'), ['worker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_worker_id'))
        batch_op.drop_index('ix_submissions_task_worker')
        batch_op.drop_index(batch_op.f('ix_submissions_task_id'))

    op.drop_table('submissions')
    with op.batch_alter_table('job_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_participants_worker_id'))
        batch_op.drop_index(batch_op.f('ix_job_participants_task_id'))

    op.drop_table('job_participants')
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disputes_task_id'))

    op.drop_table('disputes')
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_agent_id'))

    op.drop_table('webhooks')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_created')
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index('ix_jobs_buyer_id')

    op.drop_table('jobs')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_api_key_hash'))

    op.drop_table('agents')
    op.drop_table('owners')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
